module.exports = {
  bail: true,
  color: true,
  diff: true,
  parallel: false,
  timeout: 60000,
  retries: 0,
  slow: 60000,
  parallel: false,
  jobs: 1,
  // ui: "tdd",
  // recursive: true,
  // require: "src/mocha-wrapper/hooks/hooks.ts",
  reporter: "./node_modules/mochawesome",
  "reporter-option": [
    "reportTitle=XQR tests report",
    "reportPageTitle=XQR test report",
    "charts=true",
    "showPending=true",
    "overwrite=true",
    "json=false",
    "code=false",
    // 'inline=false',
    // "autoOpen=true",
  ],
};
