name: tests
on:
  pull_request:
concurrency:
  group: tests-${{github.event.pull_request.number}}
  cancel-in-progress: true
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: prepare
        run: npm i
      - name: run tests
        run: npm test
