name: tests
on:
  pull_request:
  schedule:
    # - cron: "10 */8 * * *"
    - cron: '*/5 * * * *'
concurrency:
  group: tests-${{github.event.pull_request.number}}
  cancel-in-progress: true
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v2
      - name: prepare
        run: npm ci
      - name: run tests
        run: npm test
