name: tests
on:
  pull_request:
concurrency:
  group: tests-${{github.event.pull_request.number}}
  cancel-in-progress: true
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v2
      - name: prepare
        run: pwd
      - name: prepare
        run: ls
      - name: prepare
        run: node -v
      - name: prepare
        run: npm -v
      - name: prepare
        run: npm i
      - name: run tests
        run: npm test
